CREATE TABLE CAT (
    id INTEGER NOT NULL,
    name VARCHAR2(50) NOT NULL ,
    PRIMARY KEY (id)
);

INSERT INTO CAT (ID, NAME) VALUES (100,'Sylvestre');
INSERT INTO CAT (ID, NAME) VALUES (101,'Scratch');
