CREATE TABLE DOG (
    id INTEGER NOT NULL,
    name VARCHAR2(50) NOT NULL ,
    PRIMARY KEY (id)
);

INSERT INTO DOG (ID, NAME) VALUES (100,'Salamy');
INSERT INTO DOG (ID, NAME) VALUES (101,'Scoubidou');
