CREATE TABLE PARROT
(
    id            INTEGER      NOT NULL,
    name          VARCHAR2(50) NOT NULL,
    creation_date DATETIME     NOT NULL,
    update_date   DATETIME     NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO PARROT (ID, NAME, CREATION_DATE, UPDATE_DATE)
VALUES (100, 'Pako', NOW(), NOW());
INSERT INTO PARROT (ID, NAME, CREATION_DATE, UPDATE_DATE)
VALUES (101, 'Pépin', NOW(), NOW());
